project_name: ICS RPA Service
debug: true
log_dir: log/

kafka_bootstrap_servers: localhost:9092
group_id: ics_rpa_group
fb_account_flow_queue: fb_account_flow_queue

redis_host: localhost
redis_port: 6379
redis_db: 0
redis_password: ""
redis_enabled: false

browser_headless: false
fb_user_data_dir: .browser/fb-profile
fb_default_timeout_ms: 15000

phone_pool_file: ""
